"""chat feature m1 tables

Revision ID: 348830f9c2c5
Revises: f35ce9ce2c1b
Create Date: 2026-08-23 01:04:07.094667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348830f9c2c5'
down_revision: Union[str, None] = 'f35ce9ce2c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('climate', sa.String(length=20), nullable=False),
    sa.Column('terrain', sa.JSON(), nullable=False),
    sa.Column('typical_occasions', sa.JSON(), nullable=False),
    sa.Column('suggested_categories', sa.JSON(), nullable=False),
    sa.Column('suggested_fabrics', sa.JSON(), nullable=False),
    sa.Column('avoid_fabrics', sa.JSON(), nullable=False),
    sa.CheckConstraint("climate IN ('hot-humid','hot-dry','temperate','cool','cold','rainy')", name='ck_climate_profiles_climate'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_profiles_slug'), 'climate_profiles', ['slug'], unique=True)
    op.create_table('color_palettes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('depth', sa.String(length=20), nullable=False),
    sa.Column('undertone', sa.String(length=10), nullable=False),
    sa.Column('recommended', sa.JSON(), nullable=False),
    sa.Column('de_emphasized', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("depth IN ('fair','light','medium','tan','deep','rich-deep')", name='ck_color_palettes_depth'),
    sa.CheckConstraint("undertone IN ('warm','cool','neutral','unknown')", name='ck_color_palettes_undertone'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depth', 'undertone', name='uq_color_palettes_depth_undertone')
    )
    op.create_table('daily_sales_summary',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('gross_revenue', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('net_revenue', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('aov', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('returning_customers', sa.Integer(), nullable=False),
    sa.Column('refunds_count', sa.Integer(), nullable=False),
    sa.Column('refunds_amount', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_audit_log_actor', 'admin_audit_log', ['admin_user_id', 'created_at'], unique=False)
    op.create_index('ix_admin_audit_log_tool', 'admin_audit_log', ['tool', 'created_at'], unique=False)
    op.create_table('category_performance_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('return_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'category_id', name='uq_category_performance_date_category')
    )
    op.create_index('ix_category_performance_date', 'category_performance_summary', ['date'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.CHAR(length=26), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=20), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent IN ('stylist','support','insights')", name='ck_chat_sessions_agent'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_chat_sessions_expires', 'chat_sessions', ['expires_at'], unique=False)
    op.create_index('ix_chat_sessions_user_agent', 'chat_sessions', ['user_id', 'agent', 'last_active_at'], unique=False)
    op.create_table('destination_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('climate_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['climate_profile_id'], ['climate_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('ix_destination_aliases_profile', 'destination_aliases', ['climate_profile_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.CHAR(length=26), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('tool_trace', sa.JSON(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','tool','system')", name='ck_chat_messages_role'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('product_velocity_summary',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('units_7d', sa.Integer(), nullable=False),
    sa.Column('units_30d', sa.Integer(), nullable=False),
    sa.Column('avg_daily_units_30d', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('days_of_cover', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('critical','low','watch','healthy')", name='ck_product_velocity_status'),
    sa.CheckConstraint('days_of_cover <= 999', name='ck_product_velocity_days_of_cover_cap'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index('ix_product_velocity_product', 'product_velocity_summary', ['product_id'], unique=False)
    op.create_index('ix_product_velocity_status_cover', 'product_velocity_summary', ['status', 'days_of_cover'], unique=False)
    op.create_table('tool_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=40), nullable=False),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_call_log_message', 'tool_call_log', ['message_id'], unique=False)
    op.create_index('ix_tool_call_log_tool', 'tool_call_log', ['tool', 'created_at'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.CHAR(length=26), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('requested','approved','rejected','received','refunded','cancelled')", name='ck_returns_status'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_returns_order_item', 'returns', ['order_item_id'], unique=False)
    op.create_index('ix_returns_user', 'returns', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # drop_table removes the table's own indexes for free (see every other migration in this
    # repo) — an explicit drop_index() before drop_table() risks MySQL refusing to drop an index
    # still backing a live FK constraint. Order is child-before-parent for this migration's two
    # internal FK chains: tool_call_log -> chat_messages -> chat_sessions, and
    # destination_aliases -> climate_profiles.
    op.drop_table('tool_call_log')
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    op.drop_table('destination_aliases')
    op.drop_table('climate_profiles')
    op.drop_table('product_velocity_summary')
    op.drop_table('category_performance_summary')
    op.drop_table('admin_audit_log')
    op.drop_table('daily_sales_summary')
    op.drop_table('color_palettes')
    op.drop_table('returns')
