"""climate profile style notes

Revision ID: 714147cd4d8b
Revises: e810389f3221
Create Date: 2026-08-24 01:31:48.987845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714147cd4d8b'
down_revision: Union[str, None] = 'e810389f3221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climate_profiles', sa.Column('visual_character', sa.Text(), nullable=True))
    op.add_column('climate_profiles', sa.Column('style_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climate_profiles', 'style_notes')
    op.drop_column('climate_profiles', 'visual_character')
    # ### end Alembic commands ###
