"""discovery_and_search

Revision ID: 7e6e6ca89efc
Revises: cb7fb7c4289c
Create Date: 2026-07-24 23:26:04.019335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6e6ca89efc'
down_revision: Union[str, None] = 'cb7fb7c4289c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token', sa.CHAR(length=43), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_queries_query', 'search_queries', ['query', 'created_at'], unique=False)
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('recently_viewed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_recently_viewed_user_product')
    )
    op.create_index('ix_recently_viewed_user', 'recently_viewed', ['user_id', 'viewed_at'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'product_id', name='uq_wishlist_item_product')
    )
    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'variant_id', name='uq_stock_alert_email_variant')
    )
    op.create_index('ix_stock_alerts_variant_pending', 'stock_alerts', ['variant_id', 'notified_at'], unique=False)
    # ### end Alembic commands ###

    # Spec §14.1/§14.2's MySQL FULLTEXT fallback: WITH PARSER ngram tokenises into overlapping
    # n-grams instead of whole words, so short fashion terms ("tee", "bag", "cap" — below MySQL's
    # default ft_min_word_len=4) are still indexed and substring-tolerant. Hand-written because
    # SQLAlchemy's Index construct has no portable way to express "WITH PARSER".
    op.execute(
        "ALTER TABLE products ADD FULLTEXT INDEX ft_products (title, search_keywords) WITH PARSER ngram"
    )


def downgrade() -> None:
    op.execute("ALTER TABLE products DROP INDEX ft_products")

    # ### commands auto generated by Alembic - adjusted: dropped the explicit drop_index calls on
    # ix_recently_viewed_user / ix_stock_alerts_variant_pending — both start with the FK column
    # (user_id / variant_id respectively), so MySQL uses them to back that FK constraint and
    # refuses to drop them while the table (and its FK) still exists. drop_table removes the
    # index for free, same recurring bug as the auth/commerce/inventory migrations (see done.MD). ###
    op.drop_table('stock_alerts')
    op.drop_table('wishlist_items')
    op.drop_table('wishlists')
    op.drop_table('recently_viewed')
    op.drop_table('search_queries')
    op.drop_table('newsletter_subscribers')
    # ### end Alembic commands ###
