"""mfa_challenge_remember_flag

Revision ID: 93c359557201
Revises: 67e8283370b3
Create Date: 2026-07-31 01:20:50.561568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c359557201'
down_revision: Union[str, None] = '67e8283370b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this ALTER doesn't fail under MySQL strict mode (no rows exist yet, but
    # ADD COLUMN NOT NULL still needs a default to satisfy strict SQL mode); model itself only
    # declares the ORM-level default=False, not a DB-level one, so this is migration-only.
    op.add_column(
        'mfa_challenge_tokens', sa.Column('remember', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('mfa_challenge_tokens', 'remember', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mfa_challenge_tokens', 'remember')
    # ### end Alembic commands ###
