"""reviews

Revision ID: 961a4da1cda1
Revises: 7e6e6ca89efc
Create Date: 2026-07-26 00:11:21.269008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961a4da1cda1'
down_revision: Union[str, None] = '7e6e6ca89efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('reported_count', sa.Integer(), nullable=False),
    sa.Column('moderated_by', sa.Integer(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'user_id', 'order_item_id', name='uq_review_product_user_item')
    )
    op.create_index('ix_reviews_product_status', 'reviews', ['product_id', 'status'], unique=False)
    op.create_index('ix_reviews_status_created', 'reviews', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Explicit drop_index calls on ix_reviews_product_status/ix_reviews_status_created removed:
    # the first starts with product_id (an FK column), and MySQL refuses to drop an index still
    # backing a live FK constraint until the table itself goes away — the same recurring
    # drop-order bug documented in every prior migration (see done.MD). drop_table removes both
    # indexes for free.
    op.drop_table('reviews')
