"""admin_api_keys

Revision ID: be87372a85fd
Revises: 93c359557201
Create Date: 2026-07-31 01:37:18.962695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be87372a85fd'
down_revision: Union[str, None] = '93c359557201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.CHAR(length=26), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('ip_allowlist', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('ix_api_keys_created_by', 'api_keys', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # drop_table removes the table's own index for free (see every other migration in this repo).
    op.drop_table('api_keys')
