"""inventory_and_refunds

Revision ID: cb7fb7c4289c
Revises: e39d64c1a264
Create Date: 2026-07-24 02:26:25.382235

Adjusted 2026-07-26: dropped the `inventory_movements` create_table/create_index block that used
to live here. It only existed because the original baseline migration (3b87e7cbe117) was
incomplete and didn't create `inventory_movements` even though the model existed from early on —
this migration's original autogenerate silently "adopted" it as if it were new. Now that
3b87e7cbe117 correctly creates the full catalogue schema including `inventory_movements`, creating
it again here would collide (`Table 'inventory_movements' already exists`) on a from-scratch
`alembic upgrade head` — caught by CI's fresh-database migration gate, not by inspection.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7fb7c4289c'
down_revision: Union[str, None] = 'e39d64c1a264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_refunds_order', 'refunds', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted: the explicit drop_index call preceded
    # dropping its own table, and MySQL refuses to drop an index backing a live FK constraint
    # (recurring bug — see done.MD). drop_table removes the index implicitly. `inventory_movements`
    # is no longer touched here at all — it's owned by the baseline migration now. ###
    op.drop_table('refunds')
    # ### end Alembic commands ###
