"""product velocity revenue columns

Revision ID: e810389f3221
Revises: 348830f9c2c5
Create Date: 2026-08-23 02:00:34.394521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e810389f3221'
down_revision: Union[str, None] = '348830f9c2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default='0' on both: product_velocity_summary already has rows (it's a fully-rebuilt
    # summary table, refreshed wholesale by scripts/refresh_analytics_summaries.py) — a bare
    # NOT NULL ADD COLUMN would fail against them. The next refresh run overwrites every row with
    # a real computed value anyway, so the default only matters for the instant between this
    # migration and that next run.
    op.add_column(
        'product_velocity_summary',
        sa.Column('revenue_7d', sa.DECIMAL(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'product_velocity_summary',
        sa.Column('revenue_30d', sa.DECIMAL(precision=14, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('product_velocity_summary', 'revenue_7d', server_default=None)
    op.alter_column('product_velocity_summary', 'revenue_30d', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_velocity_summary', 'revenue_30d')
    op.drop_column('product_velocity_summary', 'revenue_7d')
    # ### end Alembic commands ###
